add route user/update
akanthas-lereacteur/akanthas_backend pull request #17
Opened 2020-12-03 11:57 UTC by yayadiallo60

2020-12-03 12:15 UTC, Mobu34 requested changes

2020-12-03 12:15 UTC, Mobu34 commented on routes/user.js
>  router.put("/user/update/:id", isAuthenticated, async (req, res) => {
- je pense ça serait mieux de mettre la route en post
- pour moi pas besoin du params id car dans le isAuthenticated, on récup req.user

2020-12-03 12:15 UTC, Mobu34 commented on routes/user.js
> +    const { id } = req.params;
du coup ici tu devrais plutôt faire 
```js 
const { id } = req.user
```

2020-12-03 12:15 UTC, Mobu34 commented on routes/user.js
> +    const { lastName, firstName, userName, email, password } = req.fields;
normalement tu devrais aussi pour récupérer tous les autres champs (company, address, postalCode, city, phone) car ils y sont côté front

2020-12-03 12:15 UTC, Mobu34 commented on routes/user.js
> +    await userToUpdate.save();
le .save() te déclenche pas une erreur?

2020-12-03 13:27 UTC, Mobu34 requested changes

2020-12-03 13:27 UTC, Mobu34 commented on routes/user.js
> +      userToUpdate.token = uid2(64);
le token pour moi pas besoin de l'updater

2020-12-03 13:34 UTC, yayadiallo60 commented on routes/user.js
>  router.put("/user/update/:id", isAuthenticated, async (req, res) => {
Ok j'ai bien passé la route en poste

2020-12-03 13:34 UTC, yayadiallo60 commented on routes/user.js
> +    const { id } = req.params;
j'ai modifie et je recupere l'id avec req.user

2020-12-03 13:36 UTC, yayadiallo60 commented on routes/user.js
> +    const { lastName, firstName, userName, email, password } = req.fields;
J'ai ajouté les champs mais quand je regarde dans le signup on les recup pas apres je sais pas comment c'est coté front

2020-12-03 13:36 UTC, yayadiallo60 commented on routes/user.js
> +    await userToUpdate.save();
avec postman non pour l'insstant pas d'erreur avec. le .save

2020-12-03 13:41 UTC, yayadiallo60 commented on routes/user.js
> +      userToUpdate.token = uid2(64);
ça marche j'ai fait la modif aussi

2020-12-03 22:28 UTC, Mobu34 approved these changes

2020-12-04 08:37 UTC, MaloLebrin approved these changes

2020-12-04 08:38 UTC, nabil-ou approved these changes

2020-12-04 08:55 UTC, merged