Reset password
akanthas-lereacteur/akanthas_backend pull request #26
Opened 2020-12-07 14:48 UTC by yayadiallo60

2020-12-07 15:00 UTC, MaloLebrin requested changes

2020-12-07 15:00 UTC, MaloLebrin commented on routes/user.js
> +        userToResetPassword.resetPasswordExpires = new Date() + 3600000;
attend c'est quoi qui expires le MDP ?

2020-12-07 15:06 UTC, Mobu34 requested changes
pareil que Malo j'ai pas compris car les clés resetPasswordToken et resetPasswordExpires ne sont pas dans le model

2020-12-07 15:13 UTC, yayadiallo60 commented on routes/user.js
> +        userToResetPassword.resetPasswordToken = token;
le resetPasswordToken c'est un token qui va etre envoyé avec le mail pour etre passé en params a la route /reset.
la route /reset elle va chercher dans la BDD le token.

2020-12-07 15:13 UTC, yayadiallo60 commented on routes/user.js
> +          auth: { user: "akanthas.lereacteur@gmail.com", pass: "Phoenix20!" },
ahh mince jme suis dit je le ferais apres je coorige de suite

2020-12-07 15:47 UTC, Mobu34 commented on routes/user.js
> +        userToResetPassword.resetPasswordToken = token;
d'acc mais le model user n'a pas resetPasswordToken ni resetPasswordExpires donc comment tu stockes ces 2 infos

2020-12-07 16:33 UTC, yayadiallo60 commented on routes/user.js
> +        userToResetPassword.resetPasswordToken = token;
alors peut etre que je me trompe mais userToRese.... c'est un objet et donc je rajoute une clé a l'objet

2020-12-07 17:28 UTC, yayadiallo60 commented on routes/user.js
> +        userToResetPassword.resetPasswordToken = token;
je retire ce que j'ai dit. Effectivement dans le model il faut ces deux clé la pour que ça fonctionne

2020-12-08 17:04 UTC, Mobu34 requested changes

2020-12-09 08:34 UTC, merged